spring:
  application.name: RecipeFinder
  autoconfigure.exclude: |
    org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration,
    org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration
  ai:
    ollama:
      chat:
        model: llama3.1
        options.temperature: 1.0
      embedding.model: llama3.1
    vectorstore.redis.initialize-schema: true
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
server.tomcat.max-swallow-size: -1

app:
  always-available-ingredients: wine,salt,pepper,olive oil,broth,rice
  available-ingredients-in-fridge: bacon,onions