apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder-azure-openai
spec:
  selector:
    matchLabels:
      app: recipe-finder-azure-openai
  template:
    metadata:
      labels:
        app: recipe-finder-azure-openai
    spec:
      containers:
        - env:
          - name: SPRING_DOCKER_COMPOSE_ENABLED
            value: "false"
          - name: SPRING_PROFILES_ACTIVE
            value: azure
          - name: SPRING_AI_AZURE_OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                key: api-key
                name: recipe-finder-azure-openai
          - name: SPRING_AI_AZURE_OPENAI_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: recipe-finder-azure-openai
          - name: SPRING_AI_VECTORSTORE_REDIS_URI
            value: redis://recipe-finder-redis:6379
          image: ghcr.io/timosalm/spring-ai:recipe-finder
          imagePullPolicy: Always
          name: workload
---
apiVersion: v1
kind: Secret
metadata:
  name: recipe-finder-azure-openai
stringData:
  api-key: $SPRING_AI_AZURE_OPENAI_API_KEY
  endpoint: $SPRING_AI_AZURE_OPENAI_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-azure-openai
spec:
  type: LoadBalancer
  selector:
    app: recipe-finder-azure-openai
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder-redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        -   image: redis/redis-stack-server
            name: workload
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379